name: 'Apply the configuration and delete this repo'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 'main'

# TODO Fix token not working
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.SETUP_TOKEN }}
      TFE_TOKEN: ${{ secrets.TF_CLOUD_PERSONAL_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_PERSONAL_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          echo "tfe_owners_team_id = \"${{ vars.TFE_OWNERS_TEAM_ID }}\"" > terraform.auto.tfvars
          echo "github_token = \"${{ secrets.SETUP_TOKEN }}\"" >> terraform.auto.tfvars
          echo "tfe_token = \"${{ secrets.TF_CLOUD_PERSONAL_API_TOKEN }}\"" >> terraform.auto.tfvars
          terraform apply -auto-approve -input=false

  #delete-repo:
  #  runs-on: ubuntu-latest
  #  needs:
  #    - terraform
  #  steps:
  #    - name: Delete this repository
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.SETUP_TOKEN }}
  #      run: |
  #        echo "Deleting the current repository..."
  #        curl -X DELETE \
  #          -H "Accept: application/vnd.github+json" \
  #          -H "Authorization: token $GITHUB_TOKEN" \
  #          "https://api.github.com/repos/${{ github.repository }}"
